// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SEP_CRUD_DesignPattern.Templates.Forms
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "E:\CS\sep_crup_design_pattern\SEP_CRUD_DesignPattern\SEP_CRUD_DesignPattern\Templates\Forms\ViewTableFormDesignerTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class ViewTableFormDesignerTemplate : ViewTableFormDesignerTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("\r\nnamespace ");
            
            #line 7 "E:\CS\sep_crup_design_pattern\SEP_CRUD_DesignPattern\SEP_CRUD_DesignPattern\Templates\Forms\ViewTableFormDesignerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(generator.Namespace));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n    partial class ");
            
            #line 9 "E:\CS\sep_crup_design_pattern\SEP_CRUD_DesignPattern\SEP_CRUD_DesignPattern\Templates\Forms\ViewTableFormDesignerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(generator.Name));
            
            #line default
            #line hidden
            this.Write("<E>\r\n    {\r\n        /// <summary>\r\n        /// Required designer variable.\r\n     " +
                    "   /// </summary>\r\n        private System.ComponentModel.IContainer components =" +
                    " null;\r\n\r\n        /// <summary>\r\n        /// Clean up any resources being used.\r" +
                    "\n        /// </summary>\r\n        /// <param name=\"disposing\">true if managed res" +
                    "ources should be disposed; otherwise, false.</param>\r\n        protected override" +
                    " void Dispose(bool disposing)\r\n        {\r\n            if (disposing && (componen" +
                    "ts != null))\r\n            {\r\n                components.Dispose();\r\n            " +
                    "}\r\n            base.Dispose(disposing);\r\n        }\r\n\r\n        #region Windows Fo" +
                    "rm Designer generated code\r\n\r\n        /// <summary>\r\n        /// Required method" +
                    " for Designer support - do not modify\r\n        /// the contents of this method w" +
                    "ith the code editor.\r\n        /// </summary>\r\n        private void InitializeCom" +
                    "ponent()\r\n        {\r\n            this.btnAdd = new System.Windows.Forms.Button()" +
                    ";\r\n            this.btnUpdate = new System.Windows.Forms.Button();\r\n            " +
                    "this.btnDelete = new System.Windows.Forms.Button();\r\n            this.dgvTable =" +
                    " new System.Windows.Forms.DataGridView();\r\n            ((System.ComponentModel.I" +
                    "SupportInitialize)(this.dgvTable)).BeginInit();\r\n            this.SuspendLayout(" +
                    ");\r\n            // \r\n            // btnAdd\r\n            // \r\n            this.bt" +
                    "nAdd.Location = new System.Drawing.Point(12, 12);\r\n            this.btnAdd.Name " +
                    "= \"btnAdd\";\r\n            this.btnAdd.Size = new System.Drawing.Size(98, 33);\r\n  " +
                    "          this.btnAdd.TabIndex = 0;\r\n            this.btnAdd.Text = \"Add New\";\r\n" +
                    "            this.btnAdd.UseVisualStyleBackColor = true;\r\n            // \r\n      " +
                    "      // btnUpdate\r\n            // \r\n            this.btnUpdate.Location = new S" +
                    "ystem.Drawing.Point(116, 12);\r\n            this.btnUpdate.Name = \"btnUpdate\";\r\n " +
                    "           this.btnUpdate.Size = new System.Drawing.Size(98, 33);\r\n            t" +
                    "his.btnUpdate.TabIndex = 1;\r\n            this.btnUpdate.Text = \"Update\";\r\n      " +
                    "      this.btnUpdate.UseVisualStyleBackColor = true;\r\n            // \r\n         " +
                    "   // btnDelete\r\n            // \r\n            this.btnDelete.Location = new Syst" +
                    "em.Drawing.Point(220, 12);\r\n            this.btnDelete.Name = \"btnDelete\";\r\n    " +
                    "        this.btnDelete.Size = new System.Drawing.Size(98, 33);\r\n            this" +
                    ".btnDelete.TabIndex = 2;\r\n            this.btnDelete.Text = \"Delete\";\r\n         " +
                    "   this.btnDelete.UseVisualStyleBackColor = true;\r\n            // \r\n            " +
                    "// dgvTable\r\n            // \r\n            this.dgvTable.AllowUserToAddRows = fal" +
                    "se;\r\n            this.dgvTable.AllowUserToDeleteRows = false;\r\n            this." +
                    "dgvTable.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsM" +
                    "ode.Fill;\r\n            this.dgvTable.BackgroundColor = System.Drawing.Color.Whit" +
                    "e;\r\n            this.dgvTable.ColumnHeadersHeightSizeMode = System.Windows.Forms" +
                    ".DataGridViewColumnHeadersHeightSizeMode.AutoSize;\r\n            this.dgvTable.Lo" +
                    "cation = new System.Drawing.Point(12, 61);\r\n            this.dgvTable.Name = \"dg" +
                    "vTable\";\r\n            this.dgvTable.RowHeadersWidth = 51;\r\n            this.dgvT" +
                    "able.RowTemplate.Height = 24;\r\n            this.dgvTable.Size = new System.Drawi" +
                    "ng.Size(1079, 485);\r\n            this.dgvTable.TabIndex = 3;\r\n            // \r\n " +
                    "           // ViewTableForm\r\n            // \r\n            this.AutoScaleDimensio" +
                    "ns = new System.Drawing.SizeF(8F, 16F);\r\n            this.AutoScaleMode = System" +
                    ".Windows.Forms.AutoScaleMode.Font;\r\n            this.ClientSize = new System.Dra" +
                    "wing.Size(1133, 558);\r\n            this.Controls.Add(this.dgvTable);\r\n          " +
                    "  this.Controls.Add(this.btnDelete);\r\n            this.Controls.Add(this.btnUpda" +
                    "te);\r\n            this.Controls.Add(this.btnAdd);\r\n            this.Name = \"View" +
                    "TableForm\";\r\n            this.Text = \"ViewTableForm\";\r\n            ((System.Comp" +
                    "onentModel.ISupportInitialize)(this.dgvTable)).EndInit();\r\n            this.Resu" +
                    "meLayout(false);\r\n\r\n        }\r\n\r\n        #endregion\r\n\r\n        private System.Wi" +
                    "ndows.Forms.Button btnAdd;\r\n        private System.Windows.Forms.Button btnUpdat" +
                    "e;\r\n        private System.Windows.Forms.Button btnDelete;\r\n        private Syst" +
                    "em.Windows.Forms.DataGridView dgvTable;\r\n    }\r\n}");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public class ViewTableFormDesignerTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
