// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SEP_CRUD_DesignPattern.Templates.Models
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "E:\CS\sep_crup_design_pattern\SEP_CRUD_DesignPattern\SEP_CRUD_DesignPattern\Templates\Models\DatabaseLoaderTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class DatabaseLoaderTemplate : DatabaseLoaderTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("\r\nusing System;\r\nusing System.Collections.Generic;\r\nusing System.Data.SqlClient;\r" +
                    "\n\r\nnamespace ");
            
            #line 11 "E:\CS\sep_crup_design_pattern\SEP_CRUD_DesignPattern\SEP_CRUD_DesignPattern\Templates\Models\DatabaseLoaderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(generator.Namespace));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n    public class ");
            
            #line 13 "E:\CS\sep_crup_design_pattern\SEP_CRUD_DesignPattern\SEP_CRUD_DesignPattern\Templates\Models\DatabaseLoaderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(generator.Name));
            
            #line default
            #line hidden
            this.Write("\r\n    {\r\n        // Singleton\r\n        private static ");
            
            #line 16 "E:\CS\sep_crup_design_pattern\SEP_CRUD_DesignPattern\SEP_CRUD_DesignPattern\Templates\Models\DatabaseLoaderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(generator.Name));
            
            #line default
            #line hidden
            this.Write(" _instance = new ");
            
            #line 16 "E:\CS\sep_crup_design_pattern\SEP_CRUD_DesignPattern\SEP_CRUD_DesignPattern\Templates\Models\DatabaseLoaderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(generator.Name));
            
            #line default
            #line hidden
            this.Write("();\r\n        private DatabaseLoader() { Init(); }\r\n        public static ");
            
            #line 18 "E:\CS\sep_crup_design_pattern\SEP_CRUD_DesignPattern\SEP_CRUD_DesignPattern\Templates\Models\DatabaseLoaderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(generator.Name));
            
            #line default
            #line hidden
            this.Write(@" Instance { get => _instance ; }
        // -------------------------------------------------------------

        // Private Fields
        private SqlConnection connection;
        private SqlCommand command;

        // Properties
        public SqlConnectionStringBuilder ConnectionStringBuilder{ get; set; }

        public string DataSource { get => ConnectionStringBuilder.DataSource; }
        public string InitalCatalog { get => ConnectionStringBuilder.InitialCatalog; }
        public string UserID { get => ConnectionStringBuilder.UserID;}
        public string Password { get => ConnectionStringBuilder.Password;}

        public string ConnectionString
        {
            get
            {
                return ConnectionStringBuilder.ConnectionString;
            }
        }

        public List<string> SelectedTables { get; } = new List<string>
        {
		    ");
            
            #line 43 "E:\CS\sep_crup_design_pattern\SEP_CRUD_DesignPattern\SEP_CRUD_DesignPattern\Templates\Models\DatabaseLoaderTemplate.tt"

            
            for(int i=0; i<generator.Tables.Count; i++)
            {
                Write($"\"{generator.Tables[i].Name}\", ");
            }
            WriteLine("");
            
            
            #line default
            #line hidden
            this.Write("        };\r\n\r\n\r\n        // Private Methods\r\n        private void Init()\r\n        " +
                    "{\r\n            ConnectionStringBuilder = new SqlConnectionStringBuilder();\r\n    " +
                    "        ConnectionStringBuilder.DataSource = \"");
            
            #line 58 "E:\CS\sep_crup_design_pattern\SEP_CRUD_DesignPattern\SEP_CRUD_DesignPattern\Templates\Models\DatabaseLoaderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(generator.Builder.DataSource));
            
            #line default
            #line hidden
            this.Write("\";\r\n            ConnectionStringBuilder.InitialCatalog = \"");
            
            #line 59 "E:\CS\sep_crup_design_pattern\SEP_CRUD_DesignPattern\SEP_CRUD_DesignPattern\Templates\Models\DatabaseLoaderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(generator.Builder.InitialCatalog));
            
            #line default
            #line hidden
            this.Write("\";\r\n            ConnectionStringBuilder.UserID = \"");
            
            #line 60 "E:\CS\sep_crup_design_pattern\SEP_CRUD_DesignPattern\SEP_CRUD_DesignPattern\Templates\Models\DatabaseLoaderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(generator.Builder.UserID));
            
            #line default
            #line hidden
            this.Write("\";\r\n            ConnectionStringBuilder.Password = \"");
            
            #line 61 "E:\CS\sep_crup_design_pattern\SEP_CRUD_DesignPattern\SEP_CRUD_DesignPattern\Templates\Models\DatabaseLoaderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(generator.Builder.Password));
            
            #line default
            #line hidden
            this.Write("\";\r\n        }\r\n\r\n        private List<string> LoadAllDBTableName()\r\n        {\r\n  " +
                    "          try\r\n            {\r\n                // Prepare \r\n                OpenC" +
                    "onnection();\r\n                List<string> rs = new List<string>();\r\n           " +
                    "     command = new SqlCommand(@\"SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES" +
                    " WHERE TABLE_TYPE = \'BASE TABLE\' AND\r\n    OBJECTPROPERTY(OBJECT_ID(QUOTENAME(TAB" +
                    "LE_SCHEMA) +\r\n        N\'.\' +\r\n        QUOTENAME(TABLE_NAME)), \'IsMSShipped\') = 0" +
                    "\", connection);\r\n                command.CommandType = System.Data.CommandType.T" +
                    "ext;\r\n\r\n                // Execute\r\n                using (SqlDataReader reader " +
                    "= command.ExecuteReader())\r\n                {\r\n                    string name =" +
                    " \"\";\r\n                    while (reader.Read())\r\n                    {\r\n        " +
                    "                try\r\n                        {\r\n                            name" +
                    " = reader.GetString(0);\r\n                        }\r\n                        catc" +
                    "h (Exception)\r\n                        {\r\n                            name = \"\";" +
                    "\r\n                        }\r\n                        if (name != null && name.Le" +
                    "ngth != 0) rs.Add(name);\r\n                    }\r\n                }\r\n\r\n          " +
                    "      // Result\r\n                return rs;\r\n            }\r\n            catch (E" +
                    "xception e)\r\n            {\r\n                throw e;\r\n            }\r\n           " +
                    " finally\r\n            {\r\n                CloseConnection();\r\n            }\r\n    " +
                    "    }\r\n\r\n        private void OpenConnection()\r\n        {\r\n            try\r\n    " +
                    "        {\r\n                connection = new SqlConnection(ConnectionString);\r\n  " +
                    "              connection.Open();\r\n            }\r\n            catch (Exception e)" +
                    "\r\n            {\r\n\r\n                throw e;\r\n            }\r\n        }\r\n\r\n       " +
                    " private void CloseConnection()\r\n        {\r\n            try\r\n            {\r\n    " +
                    "            connection.Close();\r\n            }\r\n            catch (Exception e)\r" +
                    "\n            {\r\n                throw e;\r\n            }\r\n        }\r\n    }\r\n}\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public class DatabaseLoaderTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
